language: c
sudo: required
dist: trusty
script: bash -ex .travis-ci.sh
env:
  matrix:
    - OCAML_VERSION=4.02.3 LLVM_VERSION=3.8
    - OCAML_VERSION=4.02.3 LLVM_VERSION=3.9
    - OCAML_VERSION=4.03.0 LLVM_VERSION=3.8
    - OCAML_VERSION=4.03.0 LLVM_VERSION=3.9
    - OCAML_VERSION=4.04.0 LLVM_VERSION=3.8
    - OCAML_VERSION=4.04.0 LLVM_VERSION=3.9
