language: c
sudo: required
services:
  - docker
script: bash -ex .travis-ci.sh
env:
  matrix:
    - DISTRO=ubuntu-18.04 OCAML_VERSION=4.04 LLVM_VERSION=3.9
    - DISTRO=debian-unstable OCAML_VERSION=4.05 LLVM_VERSION=6.0.0
    - DISTRO=debian-unstable OCAML_VERSION=4.06 LLVM_VERSION=6.0.0
    - DISTRO=debian-unstable OCAML_VERSION=4.07 LLVM_VERSION=6.0.0
    - DISTRO=debian-unstable OCAML_VERSION=4.08 LLVM_VERSION=6.0.0
    - DISTRO=debian-unstable OCAML_VERSION=4.08 LLVM_VERSION=7.0.0
    - DISTRO=debian-unstable OCAML_VERSION=4.08 LLVM_VERSION=8.0.0
