language: c
sudo: required
dist: trusty
script: bash -ex .travis-ci.sh
env:
  matrix:
    - OCAML_VERSION=4.02.3 LLVM_VERSION=3.8
    - OCAML_VERSION=4.02.3 LLVM_VERSION=3.9
    - OCAML_VERSION=4.02.3 LLVM_VERSION=4.0 LLVM_VERSION_MICRO=.0
    - OCAML_VERSION=4.02.3 LLVM_VERSION=5.0 LLVM_VERSION_MICRO=.0
    - OCAML_VERSION=4.02.3 LLVM_VERSION=6.0 LLVM_VERSION_MICRO=.0
    - OCAML_VERSION=4.03.0 LLVM_VERSION=6.0 LLVM_VERSION_MICRO=.0
    - OCAML_VERSION=4.04.2+safe-string LLVM_VERSION=6.0 LLVM_VERSION_MICRO=.0
    - OCAML_VERSION=4.05.0 LLVM_VERSION=6.0 LLVM_VERSION_MICRO=.0
    - OCAML_VERSION=4.06.1 LLVM_VERSION=6.0 LLVM_VERSION_MICRO=.0
    - OCAML_VERSION=4.07.0 LLVM_VERSION=6.0 LLVM_VERSION_MICRO=.0
cache:
  directories:
    - $HOME/opam-cache
    - $HOME/opam-bin
