language: c
sudo: required
services:
  - docker
script: bash -ex .travis-ci.sh
env:
  matrix:
    - OCAML_VERSION=4.04 LLVM_VERSION=3.8
    - OCAML_VERSION=4.04 LLVM_VERSION=3.9
    - OCAML_VERSION=4.04 LLVM_VERSION=5.0 LLVM_VERSION_MICRO=.0
    - OCAML_VERSION=4.04 LLVM_VERSION=6.0 LLVM_VERSION_MICRO=.0
    - OCAML_VERSION=4.05 LLVM_VERSION=6.0 LLVM_VERSION_MICRO=.0
    - OCAML_VERSION=4.06 LLVM_VERSION=6.0 LLVM_VERSION_MICRO=.0
    - OCAML_VERSION=4.07 LLVM_VERSION=6.0 LLVM_VERSION_MICRO=.0
